### ISSUE TITLE
Add support for text on links

### ISSUE THREAD

**Issue by huynd2210** [huynd2210/GraphToMermaid#3]
Add support for mermaid code with texts on links. Ideally, should extract nodes, edges and the text from the mermaid.

Reference: https://mermaid.js.org/syntax/flowchart.html#text-on-links

**Comment by Dauphong123** [comment]
Solution: Use Regex

a -- description --- will use r'--\s*(.+?)\s*--- to identify description

use regex to identify if description in text or not
